---
  name: Create email
  template:
     src: "email_body.j2"
     dest: "{{ sendmail_tmp }}/email_body.txt"
  register: sendmail_file

- name: Sending email
  mail:
    host: "{{ sendmail_host }}"
    port: "{{ sendmail_port }}"
    username: "{{ sendmail_username }}"
    password: "{{ sendmail_password }}"
    to: "{{ sendmail_to }}"
    cc: "{{ sendmail_cc }}"
    subject: "{{ sendmail_subject }}"
    body: "{{ lookup('file', sendmail_file['path']) }}"
    attach: "{{ sendmail_attachments }}"
    headers: "{{ sendmail_headers }}"
    subtype: "{{ sendmail_subtype }}"
    charset: "{{ sendmail_charset }}"

- name: Cleanup
  file:
    path: "{{ sendmail_file['path'] }}"
    state: absent
